server:
  port: 8207
spring:
  application:
    name: futura-search
  datasource:
    url: jdbc:mysql://localhost:3307/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

elasticsearch:
  host: 127.0.0.1
  port: 9200

logging:
  level:
    com.futura.commerce: DEBUG
    co.elastic.clients: DEBUG
