server:
  port: 8201
spring:
  application:
    name: futura-product
  datasource:
    url: jdbc:mysql://localhost:3307/mall?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: futura-product-internal-service-secret-key-2026
  expiration: 86400000
  tokenHeader: Authorization
