server:
  port: 8083
spring:
  application:
    name: futura-order
  datasource:
    url: jdbc:mysql://localhost:3307/mall?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: futura-order-internal-service-secret-key-2026
  expiration: 86400000
  tokenHeader: Authorization
