server:
  port: 8086
spring:
  application:
    name: futura-admin
  datasource:
    url: jdbc:mysql://localhost:3307/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: futura-admin-internal-service-secret-key-2026
  expiration: 86400000
  tokenHeader: Authorization

